**Exercício 01**

Construa o operador linear diagonalizável $T:\mathbb{R}^3 \to \mathbb{R}^3$ que tenha $2$ e $9$ como autovalores de modo que os autoespaços sejam $V(2) = [(1,2,0),(0,6,1)]$ e $V(9) = [(1,1,1)]$.

In [20]:
import numpy as np

# Vetores dados
v1 = np.array([1, 2, 0], dtype=float)   # pertence a V(2)
v2 = np.array([0, 6, 1], dtype=float)   # pertence a V(2)
v3 = np.array([1, 1, 1], dtype=float)   # pertence a V(9)

# Matriz P (mudança de base)
P = np.column_stack((v1, v2, v3))

# Matriz diagonal dos autovalores (matriz de trandformação na base dada)
D = np.diag([2, 2, 9])

# Construir a matriz de transformação na base canônica
P_inv = np.linalg.inv(P)    
A = P @ D @ P_inv       # A = P D P^{-1}

print("Matriz de tranformação linear (base canônica): \n", A)
print("\nVerificando os autovetores:")
print(A @ v1)
print(A @ v2)
print(A @ v3)

Matriz de tranformação linear (base canônica): 
 [[ 4. -1.  6.]
 [ 2.  1.  6.]
 [ 2. -1.  8.]]

Verificando os autovetores:
[2. 4. 0.]
[ 0. 12.  2.]
[9. 9. 9.]


**Exercício 02**

Construa uma transformação linear que mapeia o vetor $\mathbf{v}=[1,1,1,1,1]\in\mathbb{R}^5$ nele mesmo, ou seja, a transformação deve satisfazer $\mathbf{A}\mathbf{v}=\mathbf{v}$.

In [23]:
import numpy as np

# vetor dado
v = np.array([1, 1, 1, 1, 1], dtype=float)

# construindo a matriz A = (v v^T) / (v^T v) (projeção sobre o vetor v)
A = np.outer(v, v) / np.dot(v, v)

print("Matriz A:")
print(A)

# verificamdo a matriz
print("\nA * v:")
print(A @ v)


Matriz A:
[[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]

A * v:
[1. 1. 1. 1. 1.]
